<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>theme-viewer</string>
	</array>
	<key>name</key>
	<string>Theme Viewer</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>variable.other</string>
			<key>match</key>
			<string>variable\.other</string>
			<key>name</key>
			<string>variable.other.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable.language</string>
			<key>match</key>
			<string>variable\.language</string>
			<key>name</key>
			<string>variable.language.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable.parameter</string>
			<key>match</key>
			<string>variable\.parameter</string>
			<key>name</key>
			<string>variable.parameter.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable</string>
			<key>match</key>
			<string>variable</string>
			<key>name</key>
			<string>variable.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.other</string>
			<key>match</key>
			<string>support\.other</string>
			<key>name</key>
			<string>support.other.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.variable</string>
			<key>match</key>
			<string>support\.variable</string>
			<key>name</key>
			<string>support.variable.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.constant</string>
			<key>match</key>
			<string>support\.constant</string>
			<key>name</key>
			<string>support.constant.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.type</string>
			<key>match</key>
			<string>support\.type</string>
			<key>name</key>
			<string>support.type.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.class</string>
			<key>match</key>
			<string>support\.class</string>
			<key>name</key>
			<string>support.class.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support.function</string>
			<key>match</key>
			<string>support\.function</string>
			<key>name</key>
			<string>support.function.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>support</string>
			<key>match</key>
			<string>support</string>
			<key>name</key>
			<string>support.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.other</string>
			<key>match</key>
			<string>string\.other</string>
			<key>name</key>
			<string>string.other.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.regexp</string>
			<key>match</key>
			<string>string\.regexp</string>
			<key>name</key>
			<string>string.regexp.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.interpolated</string>
			<key>match</key>
			<string>string\.interpolated</string>
			<key>name</key>
			<string>string.interpolated.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.unquoted</string>
			<key>match</key>
			<string>string\.unquoted</string>
			<key>name</key>
			<string>string.unquoted.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted.other</string>
			<key>match</key>
			<string>string\.quoted\.other</string>
			<key>name</key>
			<string>string.quoted.other.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted.triple</string>
			<key>match</key>
			<string>string\.quoted\.triple</string>
			<key>name</key>
			<string>string.quoted.triple.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted.double</string>
			<key>match</key>
			<string>string\.quoted\.double</string>
			<key>name</key>
			<string>string.quoted.double.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted.single</string>
			<key>match</key>
			<string>string\.quoted\.single</string>
			<key>name</key>
			<string>string.quoted.single.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string.quoted</string>
			<key>match</key>
			<string>string\.quoted</string>
			<key>name</key>
			<string>string.quoted.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string</string>
			<key>match</key>
			<string>string</string>
			<key>name</key>
			<string>string.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>storage.modifier</string>
			<key>match</key>
			<string>storage\.modifier</string>
			<key>name</key>
			<string>storage.modifier.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>storage.type</string>
			<key>match</key>
			<string>storage\.type</string>
			<key>name</key>
			<string>storage.type.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>storage</string>
			<key>match</key>
			<string>storage</string>
			<key>name</key>
			<string>storage.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>meta</string>
			<key>match</key>
			<string>meta</string>
			<key>name</key>
			<string>meta.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.other</string>
			<key>match</key>
			<string>markup\.other</string>
			<key>name</key>
			<string>markup.other.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.raw</string>
			<key>match</key>
			<string>markup\.raw</string>
			<key>name</key>
			<string>markup.raw.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.quote</string>
			<key>match</key>
			<string>markup\.quote</string>
			<key>name</key>
			<string>markup.quote.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.list.unnumbered</string>
			<key>match</key>
			<string>markup\.list\.unnumbered</string>
			<key>name</key>
			<string>markup.list.unnumbered.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.list.numbered</string>
			<key>match</key>
			<string>markup\.list\.numbered</string>
			<key>name</key>
			<string>markup.list.numbered.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.list</string>
			<key>match</key>
			<string>markup\.list</string>
			<key>name</key>
			<string>markup.list.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.italic</string>
			<key>match</key>
			<string>markup\.italic</string>
			<key>name</key>
			<string>markup.italic.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.heading.6</string>
			<key>match</key>
			<string>markup\.heading\.6</string>
			<key>name</key>
			<string>markup.heading.6.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.heading.5</string>
			<key>match</key>
			<string>markup\.heading\.5</string>
			<key>name</key>
			<string>markup.heading.5.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.heading.4</string>
			<key>match</key>
			<string>markup\.heading\.4</string>
			<key>name</key>
			<string>markup.heading.4.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.heading.3</string>
			<key>match</key>
			<string>markup\.heading\.3</string>
			<key>name</key>
			<string>markup.heading.3.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.heading.2</string>
			<key>match</key>
			<string>markup\.heading\.2</string>
			<key>name</key>
			<string>markup.heading.2.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.heading.1</string>
			<key>match</key>
			<string>markup\.heading\.1</string>
			<key>name</key>
			<string>markup.heading.1.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.heading</string>
			<key>match</key>
			<string>markup\.heading</string>
			<key>name</key>
			<string>markup.heading.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.bold</string>
			<key>match</key>
			<string>markup\.bold</string>
			<key>name</key>
			<string>markup.bold.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.underline.link</string>
			<key>match</key>
			<string>markup\.underline\.link</string>
			<key>name</key>
			<string>markup.underline.link.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup.underline</string>
			<key>match</key>
			<string>markup\.underline</string>
			<key>name</key>
			<string>markup.underline.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>markup</string>
			<key>match</key>
			<string>markup</string>
			<key>name</key>
			<string>markup.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword.other</string>
			<key>match</key>
			<string>keyword\.other</string>
			<key>name</key>
			<string>keyword.other.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword.operator</string>
			<key>match</key>
			<string>keyword\.operator</string>
			<key>name</key>
			<string>keyword.operator.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword.control</string>
			<key>match</key>
			<string>keyword\.control</string>
			<key>name</key>
			<string>keyword.control.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword</string>
			<key>match</key>
			<string>keyword</string>
			<key>name</key>
			<string>keyword.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>invalid.deprecated</string>
			<key>match</key>
			<string>invalid\.deprecated</string>
			<key>name</key>
			<string>invalid.deprecated.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>invalid.illegal</string>
			<key>match</key>
			<string>invalid\.illegal</string>
			<key>name</key>
			<string>invalid.illegal.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>invalid</string>
			<key>match</key>
			<string>invalid</string>
			<key>name</key>
			<string>invalid.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity.other.attribute-name</string>
			<key>match</key>
			<string>entity\.other\.attribute\-name</string>
			<key>name</key>
			<string>entity.other.attribute-name.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity.other.inherited-class</string>
			<key>match</key>
			<string>entity\.other\.inherited\-class</string>
			<key>name</key>
			<string>entity.other.inherited-class.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity.other</string>
			<key>match</key>
			<string>entity\.other</string>
			<key>name</key>
			<string>entity.other.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity.name.section</string>
			<key>match</key>
			<string>entity\.name\.section</string>
			<key>name</key>
			<string>entity.name.section.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity.name.tag</string>
			<key>match</key>
			<string>entity\.name\.tag</string>
			<key>name</key>
			<string>entity.name.tag.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity.name.type</string>
			<key>match</key>
			<string>entity\.name\.type</string>
			<key>name</key>
			<string>entity.name.type.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity.name.function</string>
			<key>match</key>
			<string>entity\.name\.function</string>
			<key>name</key>
			<string>entity.name.function.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity.name</string>
			<key>match</key>
			<string>entity\.name</string>
			<key>name</key>
			<string>entity.name.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>entity</string>
			<key>match</key>
			<string>entity</string>
			<key>name</key>
			<string>entity.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constant.other</string>
			<key>match</key>
			<string>constant\.other</string>
			<key>name</key>
			<string>constant.other.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constant.language</string>
			<key>match</key>
			<string>constant\.language</string>
			<key>name</key>
			<string>constant.language.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constant.character.escape</string>
			<key>match</key>
			<string>constant\.character\.escape</string>
			<key>name</key>
			<string>constant.character.escape.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constant.character</string>
			<key>match</key>
			<string>constant\.character</string>
			<key>name</key>
			<string>constant.character.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>constant\.numeric</string>
			<key>name</key>
			<string>constant.numeric.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constant</string>
			<key>match</key>
			<string>constant</string>
			<key>name</key>
			<string>constant.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment.block.documentation</string>
			<key>match</key>
			<string>comment\.block\.documentation</string>
			<key>name</key>
			<string>comment.block.documentation.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment.block</string>
			<key>match</key>
			<string>comment\.block</string>
			<key>name</key>
			<string>comment.block.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment.line.character</string>
			<key>match</key>
			<string>comment\.line\.character</string>
			<key>name</key>
			<string>comment.line.character.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment.line.percentage</string>
			<key>match</key>
			<string>comment\.line\.percentage</string>
			<key>name</key>
			<string>comment.line.percentage.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment.line.number-sign</string>
			<key>match</key>
			<string>comment\.line\.number\-sign</string>
			<key>name</key>
			<string>comment.line.number-sign.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment.line.double-dash</string>
			<key>match</key>
			<string>comment\.line\.double\-dash</string>
			<key>name</key>
			<string>comment.line.double-dash.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment.line.double-slash</string>
			<key>match</key>
			<string>comment\.line\.double\-slash</string>
			<key>name</key>
			<string>comment.line.double-slash.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment.line</string>
			<key>match</key>
			<string>comment\.line</string>
			<key>name</key>
			<string>comment.line.theme-viewer</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comment</string>
			<key>match</key>
			<string>comment</string>
			<key>name</key>
			<string>comment.theme-viewer</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.theme-viewer</string>
	<key>uuid</key>
	<string>e11b9ee0-d213-4cfb-8a7b-5711fbf7067b</string>
</dict>
</plist>
